-- Legacy catalog schema, captured from the database that eShopLegacyMVC creates on its first start
-- (EF6 CreateDatabaseIfNotExists plus Models/Infrastructure/*.Sequence.sql).
-- Generated by docs/legacy/capture/capture.cs. Do not edit by hand.
-- Database collation: SQL_Latin1_General_CP1_CI_AS. Objects that differ from it carry an explicit COLLATE.
-- One batch without GO separators, so it can be executed as a single command.

CREATE SEQUENCE [dbo].[catalog_brand_hilo] AS bigint START WITH 1 INCREMENT BY 10 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE;
CREATE SEQUENCE [dbo].[catalog_hilo] AS bigint START WITH 1 INCREMENT BY 10 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE;
CREATE SEQUENCE [dbo].[catalog_type_hilo] AS bigint START WITH 1 INCREMENT BY 10 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 NO CYCLE CACHE;

CREATE TABLE [dbo].[__MigrationHistory] (
    [MigrationId] nvarchar(150) NOT NULL,
    [ContextKey] nvarchar(300) NOT NULL,
    [Model] varbinary(max) NOT NULL,
    [ProductVersion] nvarchar(32) NOT NULL,
    CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED ([MigrationId] ASC, [ContextKey] ASC)
);

CREATE TABLE [dbo].[Catalog] (
    [Id] int NOT NULL,
    [Name] nvarchar(50) NOT NULL,
    [Description] nvarchar(max) NULL,
    [Price] decimal(18,2) NOT NULL,
    [PictureFileName] nvarchar(max) NOT NULL,
    [CatalogTypeId] int NOT NULL,
    [CatalogBrandId] int NOT NULL,
    [AvailableStock] int NOT NULL,
    [RestockThreshold] int NOT NULL,
    [MaxStockThreshold] int NOT NULL,
    [OnReorder] bit NOT NULL,
    CONSTRAINT [PK_dbo.Catalog] PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [dbo].[CatalogBrand] (
    [Id] int IDENTITY(1,1) NOT NULL,
    [Brand] nvarchar(100) NOT NULL,
    CONSTRAINT [PK_dbo.CatalogBrand] PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [dbo].[CatalogType] (
    [Id] int IDENTITY(1,1) NOT NULL,
    [Type] nvarchar(100) NOT NULL,
    CONSTRAINT [PK_dbo.CatalogType] PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE NONCLUSTERED INDEX [IX_CatalogBrandId] ON [dbo].[Catalog] ([CatalogBrandId] ASC);
CREATE NONCLUSTERED INDEX [IX_CatalogTypeId] ON [dbo].[Catalog] ([CatalogTypeId] ASC);

ALTER TABLE [dbo].[Catalog] ADD CONSTRAINT [FK_dbo.Catalog_dbo.CatalogBrand_CatalogBrandId] FOREIGN KEY ([CatalogBrandId]) REFERENCES [dbo].[CatalogBrand] ([Id]) ON DELETE CASCADE;
ALTER TABLE [dbo].[Catalog] ADD CONSTRAINT [FK_dbo.Catalog_dbo.CatalogType_CatalogTypeId] FOREIGN KEY ([CatalogTypeId]) REFERENCES [dbo].[CatalogType] ([Id]) ON DELETE CASCADE;
